---
:concurrency: 10
:verbose: true
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 5
  :logfile: log/sidekiq.log
staging:
  :concurrency: 5
production:
  :concurrency: 20
:queues:
  - default
  - [high, 3]
  - [low, 1]
  - [devops, 2]
